# Generated by Django 4.1.2 on 2022-10-20 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('video', models.FileField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['mp4'], message='file must be mp3')])),
            ],
        ),
    ]
